let
    // Функция List.Dates возвращает список дат
    Source = List.Dates,
    // Активируйте List.Dates function. Здесь вы сможете настроить любые извращения календаря. Но лучше использовать базисы.
    // Дата начала: # Date (YYYY,MM,DD)
    // Дата окончания:  Duration.Days(DateTime.Date(DateTime.FixedLocalNow())-  #date(YYYY, MM, DD))+1  (It counts the number of days between today and the first date of the table and adds one day more to include today).
    // Для адаптации к другим таблицам используйте этот тип столбца (YYYY; MM; DD)
    // #duration (1,0,0,0) Добавляет в List.Date по одному дню за шаг.
    #"Invoke dates" = Source(#date(2020,01,01), Duration.Days(DateTime.Date(DateTime.FixedLocalNow())- #date(2020,01,01))+1, #duration(1, 0, 0, 0)),
    // Этот шаг разворачивает таблицу, желательно ставить даты одинаковые.
    #"List to table" = Table.FromList(#"Invoke dates", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    // Переименовать столбец
    Date = Table.RenameColumns(#"List to table",{{"Column1", "Date"}}),
    // Извлекаем день, где нулевые как “00”
    #"Day Added" = Table.AddColumn(Date, "Day", each Text.PadStart(Number.ToText(Date.Day([Date])),2,"0")),
    // Извлекаем день недели, начало в понедельник.
    #"Day Name Added" = Table.AddColumn(#"Day Added", "Day Name", each Date.ToText([Date],"ddd","ru-RU")),
    // Извлекаем месяц Номер    
    #"Month No Added" = Table.AddColumn(#"Day Name Added", "Month No", each Date.Month([Date])),
    // Извлекаем название месяца
    #"Month Name Added" = Table.AddColumn(#"Month No Added", "Month Name", each Date.ToText([Date],"MMM","ru-RU")),
    // Извлекаем номер квартала
    #"Quarter No Added" = Table.AddColumn(#"Month Name Added", "Quarter No", each Date.QuarterOfYear([Date])),
    // Извлекаем недели. ВНИМАТЕЛЬНО СМОТРИТЕ НА ТО, СКОЛЬКО НЕДЕЛЬ В ГОДУ ВАМ НАДО - ЗАВИСИТ ОТ ПОЖЕЛАНИЙ КЛИЕНТА
    #"Week No added" = Table.AddColumn(#"Quarter No Added", "WeekNo", each Text.PadStart(Number.ToText(Date.WeekOfYear([Date])-1),2,"0")),
    // Извлекаем год
    #"Year Added" = Table.AddColumn(#"Week No added", "Year", each Date.Year([Date])),
    // Объединяем в ГодМесяц
    #"Year Month Added" = Table.AddColumn(#"Year Added", "Year-Month", each Number.ToText([Year])&"-"&[Month Name]),
    // Объединяем ГодКвартал
    #"Year Quarter Added" = Table.AddColumn(#"Year Month Added", "Year-Quarter", each Number.ToText([Year]) & "Q"& Number.ToText([Quarter No],"00")),
    // Изменяем тип на текст
    #"Change type to text" = Table.TransformColumnTypes(#"Year Quarter Added",{{"Year", type text}, {"Date", type date}, {"Month No", type text}, {"Day", type text}, {"Day Name", type text}, {"Month Name", type text}, {"Quarter No", type text}, {"Year-Quarter", type text}, {"Year-Month", type text}, {"WeekNo", type text}}),
    // Делаем сортировку дней
    #"Sort Day" = Table.AddColumn(#"Change type to text", "SortDay", each Date.Day([Date])),
    // Обхединяем ГодДеньНедели
    #"Sort DayName" = Table.AddColumn(#"Sort Day", "SortDayName", each Date.DayOfWeek([Date],1)),
    // Извлекаем Номер недели по Европейскому формату
    #"Sort Week No" = Table.AddColumn(#"Sort DayName", "SortWeekNo", each Date.WeekOfYear([Date])+1),
    // Делаем сортировку Недель
    #"Sort YearMonth" = Table.AddColumn(#"Sort Week No", "SortYearMonth", each [Year]&Text.PadStart([Month No],2,"0")),
    // Делаем сортировку ГодКвартал
    #"Sort YearQuarter" = Table.AddColumn(#"Sort YearMonth", "SortYearQuarter", each [Year]&Text.PadStart([Quarter No],2,"0")),
    // Изменяем тип данных сортировок на целое число
    #"Changed Type to NO" = Table.TransformColumnTypes(#"Sort YearQuarter",{{"SortYearMonth", Int64.Type}, {"SortYearQuarter", Int64.Type}, {"SortDayName", Int64.Type}, {"SortDay", Int64.Type}, {"SortWeekNo", Int64.Type}})
in
    #"Changed Type to NO"
